<?php
/**
 * @copyright Copyright © 2020 Magepow. All rights reserved.
 * @author    Magepow
 * @category Magepow
 * @copyright Copyright (c) 2014 Magepow (<https://www.magepow.com>)
 * @license <https://www.magepow.com/license-agreement.html>
 * @Author: magepow<support@magepow.com>
 * @github: <https://github.com/magepow>
 */
/** @var  Magepow\CheckoutCustomForm\Block\Order\CustomFields $block */

/** @var  Magepow\CheckoutCustomForm\Model\Data\CustomFields $customFields */
$customFields = $block->getCustomFields($block->getOrder());
?>
<?php if($customFields): ?>
    <div class="block block-order-details-view">
        <div class="block-content">
            <div class="box">
                <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Other information') ?></span></strong>
                <div class="box-content">
                    <strong><?php /* @escapeNotVerified */ echo __('Denumire Firma') ?>:</strong>
                    <?php echo $this->escapeHtml($customFields->getCheckoutDenumireFirma()); ?><br>
                    <strong><?php /* @escapeNotVerified */ echo __('CUI') ?>:</strong>
                    <?php echo $this->escapeHtml($customFields->getCheckoutCui()); ?><br>
                    <strong><?php /* @escapeNotVerified */ echo __('Nr. Reg. Com.') ?>:</strong>
                    <?php echo $this->escapeHtml($customFields->getCheckoutNrRegCom()); ?><br>

                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
